### ISSUE TITLE
Not operator is ignored on reactive queries

### ISSUE THREAD

**Issue by pablozabo** [MozillaReality/ecsy#153] opened 2020-04-08 00:53 UTC
In the following example, if I specify the Not operator on 'images' query, then the **added** list is populated with 'sprite' entities.

![image](https://user-images.githubusercontent.com/4588119/78732778-f59be780-7919-11ea-9835-d63d87b042e5.png)

Even if I try to do this:

![image](https://user-images.githubusercontent.com/4588119/78732830-23812c00-791a-11ea-96b0-1754e70d848c.png)

the result is the same.

**Comment by fernandojsg** [comment] 2020-05-24 12:52
@pablozabo can you provide an example or test? I tried to reproduce it by adding a test and I'm not able to get the issue you mention, maybe I'm missing something. This is the test I just added to check it https://github.com/MozillaReality/ecsy/commit/ecf03ffb78e755d59e764c542696bca466c76998

**Comment by fernandojsg** [comment] 2020-07-30 15:31
I was reviewing the testing for reactive queries and I can't reproduce it. Closing it, please feel free to reopen if your issue continues

**Closed by fernandojsg** 2020-07-30 15:31 UTC
Labels: need info
